// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvwtikkltashkvreqhfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2d3Rpa2tsdGFzaGt2cmVxaGZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MzU0MTUsImV4cCI6MjA2NDIxMTQxNX0.gffIaOG3BXYhhNKUO5aa231YZpBv0Y8-4QqjGG40wuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);